require("dotenv").config();

const { Client } = require("pg");

const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: {
        rejectUnauthorized: false
    }
});

async function createSchema() {
    try {
        await client.connect();

        console.log("Connected to Neon PostgreSQL.");

        await client.query(`
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'customer',
                active INTEGER NOT NULL DEFAULT 1,
                package TEXT DEFAULT NULL,
                name TEXT DEFAULT NULL,
                email TEXT DEFAULT NULL
            );

            CREATE TABLE IF NOT EXISTS courses (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                description TEXT,
                video_url TEXT
            );

            CREATE TABLE IF NOT EXISTS lessons (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                course_id INTEGER NOT NULL,
                title TEXT NOT NULL,
                description TEXT,
                video_url TEXT,
                lesson_order INTEGER DEFAULT 0,
                FOREIGN KEY (course_id)
                    REFERENCES courses(id)
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS user_courses (
                user_id INTEGER NOT NULL,
                course_id INTEGER NOT NULL,
                progress INTEGER DEFAULT 0,
                PRIMARY KEY (user_id, course_id)
            );

            CREATE TABLE IF NOT EXISTS user_lesson_progress (
                user_id INTEGER NOT NULL,
                lesson_id INTEGER NOT NULL,
                completed INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (user_id, lesson_id),
                FOREIGN KEY (user_id)
                    REFERENCES users(id)
                    ON DELETE CASCADE,
                FOREIGN KEY (lesson_id)
                    REFERENCES lessons(id)
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS course_payments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                course_id INTEGER NOT NULL,
                total_fee INTEGER DEFAULT 0,
                amount_paid INTEGER DEFAULT 0,
                UNIQUE(user_id, course_id)
            );

            CREATE TABLE IF NOT EXISTS enrollment_requests (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                course_id INTEGER NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id)
                    REFERENCES users(id)
                    ON DELETE CASCADE,
                FOREIGN KEY (course_id)
                    REFERENCES courses(id)
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS password_requests (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                message TEXT,
                created_at TEXT,
                FOREIGN KEY (user_id)
                    REFERENCES users(id)
                    ON DELETE CASCADE
            );

                        CREATE TABLE IF NOT EXISTS reviews (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL UNIQUE,
                rating INTEGER NOT NULL
                    CHECK (rating BETWEEN 1 AND 5),
                review TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id)
                    REFERENCES users(id)
                    ON DELETE CASCADE
            );

        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS orphaned_reviews (
                id INTEGER PRIMARY KEY,
                original_user_id INTEGER NOT NULL,
                rating INTEGER NOT NULL,
                review TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        `);

        console.log("All PostgreSQL tables created successfully.");

        console.log("All PostgreSQL tables created successfully.");

    } catch (error) {
        console.error("Schema creation failed:", error.message);
    } finally {
        await client.end();
    }
}

createSchema();